new tf workflow
NASA-PDS/template-repo-python pull request #69
Opened 2023-07-06 22:01 UTC by sjoshi-jpl

## 🗒️ Summary
Add new terraform cicd workflow

## ⚙️ Test Data and/or Report
Note: the tests will fail since it's looking for repository variables which cannot be supplied as these are just example templates.

## ♻️ Related Issues

Ref - https://github.com/NASA-PDS/devops/issues/52

2023-07-10 16:14 UTC, jordanpadams requested changes

2023-07-10 17:59 UTC, sjoshi-jpl commented on .github/workflows/terraform_cicd.yaml
> +    types: [opened, edited, reopened, ready_for_review, review_requested]
@jordanpadams yes but I can limit the number of times this workflow gets executed by only running terraform plan on PR creation and push to main.

https://github.com/NASA-PDS/nucleus/pull/56#pullrequestreview-1522517881

2023-07-11 16:43 UTC, nutjob4life approved these changes
👍

2023-07-11 19:45 UTC, jordanpadams approved these changes

2023-07-11 19:59 UTC, jordanpadams approved these changes

2023-07-12 01:26 UTC, merged